### ISSUE TITLE
Interne Pages

### ISSUE THREAD

**Issue by Vento-Nuenenen** [mischahaenen/nuenenen#5]
Mechanik für interne Seiten.
Diese sind nicht im Sitemap, durch die Robots ausgeschlossen und man muss für den Zugriff eingeloggt sein.
Keine Verlinkung im Menü, variabel nur für Angemeldete Nutzer.

Soll dazu Dienen, Informationen für die Leiter zur verfügung zu stellen.
 Bsp. Linksammlung, WoWo Abrechnung.

**Comment by mischahaenen** [comment]
Sollte durch Rollenkonzept abgedeckt sein.
